name: image-analysis-24
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - jupytext
  - jupyterlab-myst
  - notebook
  - matplotlib
  - scikit-image=0.24.0
  - jupyter-book=1.0.0
  - pooch=1.8.2
  - scikit-learn=1.5.0
  - ipywidgets=8.1.3
  - seaborn=0.13.2
  - napari=0.4.19.post1
  - napari-animation
  - cookiecutter
  - pyqt
